import type { Activity, Sales } from '../types';

export const generateDailyDigest = (
  salesData: Sales[],
  activities: Activity[],
  date: Date
) => {
  const dStr = date.toLocaleDateString('id-ID', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' });
  let text = `📊 *DAILY SALES DIGEST*\n📅 ${dStr}\n`;
  text += `────────────────────\n\n`;

  // Start of Day / End of Day boundary
  const start = new Date(date); start.setHours(0, 0, 0, 0);
  const end = new Date(date); end.setHours(23, 59, 59, 999);
  
  const actsToday = activities.filter(a => {
    const d = new Date(a.timestamp);
    return d >= start && d <= end;
  });

  let totalV = 0; let totalP = 0; let totalC = 0; let totalWA = 0;

  salesData.forEach(s => {
    const sActs = actsToday.filter(a => a.id_sales === s.id);
    const sVisits = sActs.filter(a => a.tipe_aksi === 'Visit').length;
    const sWA = sActs.filter(a => a.tipe_aksi === 'WA').length;
    const sPros = sActs.filter(a => a.target_type === 'prospek').length;
    const sCust = sActs.filter(a => a.target_type === 'customer').length;
    const closings = sActs.filter(a => a.catatan_hasil.toLowerCase().includes('closing')).length;

    totalV += sVisits; totalP += sPros; totalC += sCust; totalWA += sWA;

    text += `👤 *Sales ${s.nama.split(' ')[0]}*\n`;
    text += `📍 Visit: ${sVisits} toko\n`;
    text += `💬 WhatsApp: ${sWA} chat\n`;
    text += `🌱 Prospek Baru Dihubungi: ${sPros}\n`;
    text += `🔁 Maintenance Customer: ${sCust}\n`;
    if (closings > 0) text += `🏆 *CLOSING: ${closings} DEAL!* 🔥\n`;
    text += `\n`;
  });

  text += `────────────────────\n`;
  text += `*⚠️ RANGKUMAN HARI INI*\n`;
  text += `Total Visit Keseluruhan: *${totalV} toko*\n`;
  text += `Total Prospek Disihi: *${totalP} prospect*\n`;
  text += `📝 _Pastikan input data lengkap dengan foto geotag GPS di aplikasi PT. Industri Keluarga Timur agar valid._\n\n`;
  text += `✅ _Generated by IKT System_`;

  return text;
};
